# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Bruning's Brain Dump
tagline:          ''
description:      'My bitches gripes and complaints'
url:              http://github.com/ebruning

author:
  name:           'Ethan Bruning'
  url:            https://twitter.com/ethan_bruning

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/ebruning/ebruning.github.io
